import React, { useEffect, useMemo, useState } from 'react';
import './wizard.css';
import BikeTypeStep from './BikeTypeStep';
import PresetStep from './PresetStep';
import AdvancedStep from './AdvancedStep';
import QuestionsStep from './QuestionsStep';
import { totalMinutes, roundHalf } from './budget';

const STEPS = ['Bike', 'Style', 'Fine-tune', 'Questions'];

/**
 * Four-step preset wizard (primary profile-creation flow).
 * Config comes from GET /preset_config (generated by generate_preset_config.py);
 * saving posts a schema-v2 profile to POST /profiles.
 */
export default function PresetWizard({ apiBase, themeMode, onClose, onCreated }) {
  const [config, setConfig] = useState(null);
  const [loadError, setLoadError] = useState('');
  const [step, setStep] = useState(0);

  const [bikeType, setBikeType] = useState(null);
  const [preset, setPreset] = useState(null);
  const [weights, setWeights] = useState({});
  const [budget, setBudget] = useState(10);
  const [toggles, setToggles] = useState({
    light_night: false,
    surface: false,
    jam_comfort: true,
    vf_infrastructure: { shared_path: true, bus_lane: true },
  });
  const [name, setName] = useState('');
  const [saveError, setSaveError] = useState('');
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    let cancelled = false;
    fetch(`${apiBase}/preset_config`)
      .then((r) => r.json())
      .then((data) => {
        if (cancelled) return;
        if (data.error) setLoadError(data.error);
        else setConfig(data);
      })
      .catch(() => { if (!cancelled) setLoadError('Could not load preset configuration.'); });
    return () => { cancelled = true; };
  }, [apiBase]);

  const selectPreset = (id) => {
    setPreset(id);
    const p = config.presets[id];
    setWeights({ ...p.weights });
    setToggles((prev) => ({
      ...prev,
      ...p.toggles,
      vf_infrastructure: prev.vf_infrastructure,
    }));
    const est = p.estimated_detour_min_by_bike?.[bikeType || 'standard'] ?? 10;
    setBudget(Math.max(5, Math.ceil(est)));
  };

  const handleWeightChange = (key, value) => {
    setWeights((prev) => ({ ...prev, [key]: value }));
  };

  const handleToggleChange = (key, value) => {
    setToggles((prev) => ({ ...prev, [key]: value }));
  };

  const estUsed = useMemo(() => {
    if (!config || !bikeType) return 0;
    return roundHalf(totalMinutes(config.sliders, weights, bikeType));
  }, [config, weights, bikeType]);

  const buildPayloadWeights = () => {
    const w = {};
    Object.keys(config.sliders).forEach((k) => { w[k] = weights[k] ?? 0; });
    const rules = config.bike_types[bikeType]?.rules || {};
    if (rules.hill_weight_epsilon) w.hill_weight = config.epsilon;

    const t = config.toggles;
    w.light_weight = toggles.light_night ? t.light_night.on_value : 0;
    if (rules.surface_auto_value) w.surface_weight = rules.surface_auto_value;
    else w.surface_weight = toggles.surface ? t.surface.on_value : 0;
    w.tfl_live_weight = toggles.jam_comfort
      ? t.jam_comfort.comfortable_value
      : t.jam_comfort.cautious_value;
    return w;
  };

  const handleSave = async () => {
    setSaveError('');
    if (!name.trim()) { setSaveError('Give your profile a name.'); return; }
    setSaving(true);
    try {
      const res = await fetch(`${apiBase}/profiles`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name: name.trim(),
          weights: buildPayloadWeights(),
          bike_type: bikeType,
          preset,
          toggles,
        }),
      });
      const data = await res.json();
      if (!res.ok) { setSaveError(data.error || 'Failed to save profile.'); return; }
      onCreated(data);
    } catch {
      setSaveError('Backend connection error.');
    } finally {
      setSaving(false);
    }
  };

  const canNext = (step === 0 && !!bikeType) || (step === 1 && !!preset) || step === 2;
  const isLast = step === STEPS.length - 1;

  const body = () => {
    if (loadError) return <p className="wiz-intro">{loadError}</p>;
    if (!config) return <p className="wiz-intro">Loading preset configuration…</p>;
    if (step === 0) return <BikeTypeStep config={config} bikeType={bikeType} onSelect={setBikeType} />;
    if (step === 1) return <PresetStep config={config} bikeType={bikeType} preset={preset} onSelect={selectPreset} />;
    if (step === 2) {
      return (
        <AdvancedStep
          config={config}
          bikeType={bikeType}
          preset={preset}
          weights={weights}
          onWeightChange={handleWeightChange}
          budget={budget}
          onBudgetChange={setBudget}
        />
      );
    }
    return (
      <QuestionsStep
        config={config}
        bikeType={bikeType}
        toggles={toggles}
        onToggleChange={handleToggleChange}
        name={name}
        onNameChange={setName}
      />
    );
  };

  return (
    <div className="wiz-overlay" onMouseDown={(e) => { if (e.target === e.currentTarget) onClose(); }}>
      <div className="wiz-root" data-theme={themeMode}>
        <div className="wiz-header">
          <div className="wiz-header-row">
            <span className="wiz-title">New riding profile</span>
            <button type="button" className="wiz-close" onClick={onClose} aria-label="Close">✕</button>
          </div>
          <div className="wiz-steps">
            {STEPS.map((label, i) => (
              <div key={label} className={`wiz-step-dot${i <= step ? ' active' : ''}`} />
            ))}
          </div>
          <div className="wiz-step-label">
            Step {step + 1} of {STEPS.length} — {STEPS[step]}
          </div>
        </div>

        <div className="wiz-body">{body()}</div>

        <div className="wiz-footer">
          {step > 0 ? (
            <button type="button" className="wiz-btn" onClick={() => setStep(step - 1)}>
              Back
            </button>
          ) : <span />}
          {step >= 2 && config && bikeType && (
            <span className="wiz-est-line">
              Estimated detour: <strong>{estUsed} min</strong>
            </span>
          )}
          {saveError && <span className="wiz-error">{saveError}</span>}
          {!isLast ? (
            <button
              type="button"
              className="wiz-btn primary"
              disabled={!canNext || !config}
              onClick={() => setStep(step + 1)}
            >
              Continue
            </button>
          ) : (
            <button
              type="button"
              className="wiz-btn primary"
              disabled={saving || !name.trim()}
              onClick={handleSave}
            >
              {saving ? 'Saving…' : 'Save profile'}
            </button>
          )}
        </div>
      </div>
    </div>
  );
}
